### ISSUE TITLE
Implement godot 4.2's extension hot reloading

### ISSUE THREAD

**Issue by ShirenY** [grow-graphics/gd#19]
This is a feature request. As game projects grow larger, it becomes crucial for developers to change code and run tests within the editor. Most commercial projects need to keep the editor always running to avoid reload times.

In Godot 4.2, they introduced in-editor extension [hot reloading](https://godotengine.org/article/godot-4-2-arrives-in-style/#gdextension). gd, as a language plugin, should adopt this feature to enable faster iteration for developers.

**Comment by Splizard** [comment]
Thanks for the proposal, this is certainly something we'd like to support. I'm somewhat aware of hot reloading, it requires `recreate_instance` to be implemented. I'll track any progress towards this here.

**Comment by Splizard** [comment]
Waiting on a resolution for https://github.com/godotengine/godot/issues/92063, if I work around this particular issue by patching Godot with an if check, hot-reloading seems to be working fine.

**Comment by Splizard** [comment]
This is one of the reasons I don't like C/C++, you hit a segfault and the API designer says that you need to call some special required (but not documented as such) function when you set things up, so that when you hot reload, the engine doesn't crash 🤷

I just pass nil values to this "required" function and now everything works.

Still have no idea what "instance bindings" are intended to be used for but oh well, hot reloading work now on Godot stable!

**Comment by ShirenY** [comment]
I don't know the low-level details, but from the context, it seems that for a particular instance in the engine, you need to bind the instance (wrapper) in go to it. If this binding is not done, something goes wrong.

I guess the instances is refers to custom object types?
