### ISSUE TITLE
Can't create a custom resource type and load it with gd 

### ISSUE THREAD

**Issue by ShirenY** [grow-graphics/gd#20]
Hi,
It's me again. I've encountered another issue (actually two issues) while trying to create my custom asset.

The asset is a list of PackedScene, which I created easily with GDScript. However, in gd, I encountered two issues:

1. gd.ArrayOf does not exist. I found gd.ArrayOf in the internal code, and I saw many functions using it to return various lists. I wanted to try it, but the compiler tells me it can't find ArrayOf, which is confusing. Is there something I'm missing?

2. can't load the custom asset with the gd.Load() function because it needs a type that implements the isResource interface. If I define an AsResource function for it, it compiles, but is this the correct way to do it?

```go
package main

import (
	//"unsafe"
	"grow.graphics/gd"
	"grow.graphics/gd/gdextension"
)

type TestLib struct {
	gd.Class[TestLib, gd.Resource] `gd:"TestLib"`

	CompPrefabs gd.ArrayOf[gd.PackedScene] // ERROR: no ArrayOf
}

// This function will make gd.Load compile, but is it right way to do?
//func (l TestLib) AsResource() gd.Resource { return *(*gd.Resource)(unsafe.Pointer(&l)) }

func InitLib(ctx gd.Context) {
	gd.Load[TestLib](ctx, "TestLib.tres") //  ERROR: TestLib dose not fit isResource
}

func main() {
	godot, ok := gdextension.Link()
	if !ok {
		panic("could not link to godot")
	}

	gd.Register[TestLib](godot)
}
```

**Comment by Splizard** [comment]
Thanks again for reporting the issues you've been running into. I encourage you to keep opening issues when you run into problems, or opening discussions when you have questions 👍 

1. Yep this is an issue, Go doesn't support type aliases for generics, the generic arrays are defined in the internal packages and can't be exported via alias like the other named types can. Go is adding support for this in 1.23, I'll have another look at this but in the meantime, the generic support may be better off removed and all arrays can be exposed as the dynamic `gd.Array` type.
2. `gd.Load` is intended to be an equivalent to GDScript `load` with the additional requirement that the type of the resource being loaded needs to be defined upfront (this determines the return type). If `TestLib.tres` is known to be of type `TestLib` then this should work. Otherwise you could pass `gd.Resource` as the type parameter if you don't know what the exact resource type is, as all resource types must extend resource. Then you could do a type-assertion (in Godot terms, attempt to cast to another class) at a later point (this is what `gd.Load` is designed to do when you specify the type).

**Comment by ShirenY** [comment]
I’m completely comfortable with implementing a workaround for the array if there are language limitations. However, could you provide more details on how to export (display in the inspector) a specific type of Array in gd? If my property is defined as an Array, how does the engine determine the type of its elements? Is there a method to relay this information from gd to the engine?

**Comment by ShirenY** [comment]
> 2\. `gd.Load` is intended to be an equivalent to GDScript `load` with the additional requirement that the type of the resource being loaded needs to be defined upfront (this determines the return type). If `TestLib.tres` is known to be of type `TestLib` then this should work. Otherwise you could pass `gd.Resource` as the type parameter if you don't know what the exact resource type is, as all resource types must extend resource. Then you could do a type-assertion (in Godot terms, attempt to cast to another class) at a later point (this is what `gd.Load` is designed to do when you specify the type).

there may be some confusion. My point is that the gd.Load() function call cannot compile until I define an asResource() method for my custom resource type. I don’t believe this is a convenient or appropriate approach. However, it’s reassuring to know that if the asset exists, it will load without any problems.

**Comment by Splizard** [comment]
> until I define an asResource() method

Ah, yes, you probably shouldn't use `unsafe` for this, such a method can be implemented like this:
```go
func (l TestLib) AsResource() gd.Resource { return l.Super() }
```

**Comment by ShirenY** [comment]
> ```go
> func (l TestLib) AsResource() gd.Resource { return l.Super() }
> ```

Can confirm this works.

**Comment by Splizard** [comment]
The property will appear in the inspector now, note that there isn't a subtype hint yet, this will certainly come after the release of Go 1.23. You can still choose a value here, it's just not restricted to the specific type you want (which means there is a big annoying menu). We may be able to add a special struct tag to specify the subtype by name. Let me know your thoughts.
![image](https://github.com/grow-graphics/gd/assets/2015791/55bdb97d-b8b7-43cf-abda-b54e587b4194)

**Comment by ShirenY** [comment]
Array finally works! Thanks.

> this will certainly come after the release of Go 1.23
It's really unfortunate that untyped arrays are difficult to use in both the inspector and the code. Perhaps you could close this ticket and open another one specifically for exporting typed arrays.

**Comment by Splizard** [comment]
`gd.ArrayOf[gd.PackedScene]` should work now, have implemented a solution using interfaces.
