### ISSUE TITLE
use after free Error on gd.String properties

### ISSUE THREAD

**Issue by devnull-twitch** [grow-graphics/gd#25]
Having a gd.String property and editing that in the Godot Editor results in the following error:

```
panic: runtime.link/mmm error: use after free

goroutine 17 [running, locked to thread]:
grow.graphics/gd/internal.Context.Variant({{0x7fffbe11b220?, 0xc0002fc450?}, 0x7fffbf0c4240?}, {0x7fffbe11b220, 0xc0005976d0})
        C:/Users/***/go/pkg/mod/grow.graphics/gd@v0.0.0-20240606113431-f7a9dfc4c64b/internal/variant_conversions.go:42 +0x19f4
grow.graphics/gd.(*instanceImplementation).Get(0xc0005c97a0, {{}, {0x7fffbdfcd600?, 0xc0003ec390?}})
        C:/Users/***/go/pkg/mod/grow.graphics/gd@v0.0.0-20240606113431-f7a9dfc4c64b/register_class.go:345 +0x2f7
grow.graphics/gd/gdextension.get_func(0x4, 0x572a3fe470, 0x572a3fe320)
        C:/Users/***/go/pkg/mod/grow.graphics/gd@v0.0.0-20240606113431-f7a9dfc4c64b/gdextension/gdextension_interface.go:2379 +0x15a
exit status 2
```

Sample Code:

```go
package main

import (
	"grow.graphics/gd"
	"grow.graphics/gd/gdextension"
)

type HelloWorld struct {
	gd.Class[HelloWorld, gd.Node]

	DummyString gd.String `gd:"dummy_string"`
}

func main() {
	godot, ok := gdextension.Link()
	if !ok {
		panic("Unable to link to godot")
	}
	gd.Register[HelloWorld](godot)
}
```

**Comment by Splizard** [comment]
Thanks for reporting, this issue has been fixed.

**Comment by devnull-twitch** [comment]
Reading a string coming from Godot works fine now. But when I do set the string it does still error.

Sample go code:
```go
package main

import (
	"grow.graphics/gd"
	"grow.graphics/gd/gdextension"
)

type HelloWorld struct {
	gd.Class[HelloWorld, gd.Node]

	DummyString gd.String `gd:"dummy_string"`
}

func (h *HelloWorld) Ready(godoCtx gd.Context) {
	h.DummyString = godoCtx.String("Test")
}

func main() {
	godot, ok := gdextension.Link()
	if !ok {
		panic("Unable to link to godot")
	}
	gd.Register[HelloWorld](godot)
}
```

Sample gdscript code on other node trying to read string
```gdscript 
extends Label

@onready var hello_world_node: Node = get_node_or_null("../HelloWorld")

func _ready():
  if hello_world_node == null:
    return

  text = hello_world_node.dummy_string
```

With a scene like this
![image](https://github.com/grow-graphics/gd/assets/97809736/0603a7cd-e681-487b-bde0-49b55026f544)

**Comment by Splizard** [comment]
Thanks, the error here is expected, since `godoCtx.String("Test")` is a Godot reference type and only lives until the end of the function. You would need to pin/associate the lifetime of the string with the class, in order to resolve this issue. Something like this:

```go
func (h *HelloWorld) Ready(godoCtx gd.Context) {
	h.DummyString = h.Pin().String("Test")
}
```

I understand this is not exactly straightforward, nor readily readable, you may like to contribute to the discussion here 
https://github.com/grow-graphics/gd/discussions/16

I have some ideas to make this more intuitive/readable, perhaps removing Context parameters as a requirement for methods and using the class itself to access the Godot GlobalScope (and to manage lifetimes).
